[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v -ra
markers =
    availability: проверка доступности сервиса
    balance: проверка запроса баланса
    payment_create: создание платежа
    payment_execute: исполнение платежа
    contract: проверка соответствия ответа документации (контракт)
